version: "3"
services: 
  mongodb: #container name
  image: mongo #image name
  ports: 
  - 27017:27017
  environment: 
  - MONGO_INITDB_ROOT_USERNAME=admin
  - MONGO_INITDB_ROOT_PASSWORD=password
  mongoexpress:
  image: mongo-express
  ports: 
  - 8080:8081
  environment:
  - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  - ME_CONFIG_MONGODB_SERVER=mongodb

  #commands: 
  #docker-compose mongo-compose.yaml up
  #docker-compose mongo-compose.yaml up -d 
  
  # note: docker-compose mongo-compose.yaml down ==> it will remove the containers and networking also
  # while compose file is up there is a network will be created to communicating two containers.
