apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    env: dev
spec: 
containers: 
- name: nginx
  image: nginx:latest
  ports: 
    containerPort: 80
nodeSelector:
  disk: ssd


# to show all labels
#kubectl get nodes --show-labels
