apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector: nginx-app
  template:
     metadata:
       name: nginx-pod
       labels: 
         app: nginx-app
     spec:
       containers:
       - name: nginx-container
         image: nginx
         ports: 
         - containerPort: 80
